### ISSUE TITLE
Implement nested generation

### ISSUE THREAD

**Issue by VEINHORN** [VEINHORN/android-layout-plugin#2]
```yaml
LinearLayout:
  TextView:
    id: (myid1, myid2, myid3)
    layout_width: 20dp
    layout_height: 30dp
  LinearView:
    TextView:
      -
        id: (yoid1, yoid2, yoid3)
        text: some text
      -
        text: some text 2
```
